function registry = MODsetup_metadata_field_registry()
% MODsetup_metadata_field_registry        Part of MOD_fish_processing
%
% registry = MODsetup_metadata_field_registry()
%
% DESCRIPTION
%   The single source of truth for every deployment-tunable value this
%   repo currently knows how to read from setup.yml: where it lives in
%   setup.yml (yaml_section/yaml_key), where it lives in metadata
%   (metadata_path), what it's for, and what value it has historically
%   defaulted to. Consumed by MODsetup_validate_metadata.m (looks up each
%   requested name to know what to check/prompt for) and
%   MODsetup_write_yaml_value.m callers (to know which section/key to
%   write). Not consumed by MODsetup_read_yaml.m - that function only ever
%   sets a metadata field when setup.yml actually declares it (see its
%   header); suggested_default here is purely the starting value shown in
%   MODsetup_prompt_value.m's popup, never applied silently.
%
%   The 10 PROCESS.CHI entries, 6 of the 7 profile-picking entries
%   (modProcess_detect_profiles.m; profile_dir is validated in
%   MODprocess_single_L1_to_L2_profile.m instead - it gates epsi spectra,
%   not profile detection), epsi_gap_factor
%   (modProcess_extract_profile.m), and fft_length/fft_segments_per_scan/
%   scan_overlap (mod_scan_get_spectra.m, mod_L2_tile_scans.m,
%   mod_scan_calc_chi_mle.m - scan_length is derived from the first two,
%   dof from fft_segments_per_scan alone, neither is its own entry) have
%   real MODsetup_validate_metadata.m call sites.
%   PROFILES.lowpass_factor/.ctd_gap_factor/.buffer_bins are populated so
%   this table stays a complete, accurate record of every yaml-configurable
%   value, even though wiring their consumer
%   (mod_L1_detect_profiling_direction.m) is a deferred follow-up - see
%   PLAN.md. The 14 PROCESS.EPSILON entries and
%   PROCESS.GRID.dz_m are the same situation, one step further out: no
%   MODsetup_validate_metadata.m call site exists yet because no epsilon,
%   profile-QC, or gridding module exists yet either
%   (mod_scan_calc_epsilon.m/modProcess_L2_qc.m/
%   modProcess_L3_grid_profiles.m are all "Not started" in PLAN.md Section
%   6.4/6.5) - registered now from a review of Jen's ASTRAL reprocessing
%   fork so the parameters those modules will need aren't lost before
%   they're built. See PLAN.md Session Log, 2026-09-02.
%
% OUTPUTS
%   registry - struct array (1 x 39), one entry per value:
%     name              - short key used in MODsetup_validate_metadata.m's
%                          list_of_variables, e.g. 'kmin_obs'
%     yaml_section       - top-level setup.yml block, e.g. 'chi'
%     yaml_key           - key within that block, e.g. 'kmin_obs'
%     metadata_path      - cellstr of nested metadata field names, e.g.
%                          {'PROCESS','CHI','kmin_obs'}
%     description        - human-readable, shown in MODsetup_prompt_value.m
%     suggested_default  - this function's historical hardcoded value,
%                          shown as the prompt's starting value only
%
% CALLED BY
%   MODsetup_validate_metadata.m
%
% CALLS
%   (none)
%
% Multiscale Ocean Dynamics (MOD) Group, Scripps Institution of Oceanography

registry = struct('name', {}, 'yaml_section', {}, 'yaml_key', {}, ...
    'metadata_path', {}, 'description', {}, 'suggested_default', {});

registry(end+1) = entry('time_constant_s', 'chi', 'time_constant_s', ...
    {'PROCESS', 'CHI', 'time_constant_s'}, ...
    ['FP07 time-constant coefficient tau0 [s] (mod_scan_fpo7_transfer_function.m: ' ...
     'tau = tau0*abs(w)^exponent)'], ...
    0.0083);

registry(end+1) = entry('fall_speed_exponent', 'chi', 'fall_speed_exponent', ...
    {'PROCESS', 'CHI', 'fall_speed_exponent'}, ...
    ['FP07 time-constant fall-speed exponent (mod_scan_fpo7_transfer_function.m: ' ...
     'tau = tau0*abs(w)^exponent)'], ...
    -0.32);

registry(end+1) = entry('noise_adjusted_to_f', 'chi', 'noise_adjusted_to_f', ...
    {'PROCESS', 'CHI', 'noise_adjusted_to_f'}, ...
    ['Fraction of f(end) (Nyquist) above which mod_scan_fpo7_cutoff.m normalizes ' ...
     'the observed spectrum onto the bench noise floor''s scale'], ...
    0.7);

registry(end+1) = entry('n_smooth_f_spectrum', 'chi', 'n_smooth_f_spectrum', ...
    {'PROCESS', 'CHI', 'n_smooth_f_spectrum'}, ...
    ['movmean smoothing window [bins] applied to the observed spectrum before ' ...
     'the noise-floor search (mod_scan_fpo7_cutoff.m)'], ...
    15);

registry(end+1) = entry('sn_min', 'chi', 'sn_min', ...
    {'PROCESS', 'CHI', 'sn_min'}, ...
    ['Signal-to-noise multiplier: the noise-floor cutoff is where the smoothed ' ...
     'spectrum drops below sn_min x the bench noise floor (mod_scan_fpo7_cutoff.m)'], ...
    3);

registry(end+1) = entry('n_skip', 'chi', 'n_skip', ...
    {'PROCESS', 'CHI', 'n_skip'}, ...
    'Number of lowest-frequency bins excluded from the noise-floor search (mod_scan_fpo7_cutoff.m)', ...
    2);

registry(end+1) = entry('kmin_obs', 'chi', 'kmin_obs', ...
    {'PROCESS', 'CHI', 'kmin_obs'}, ...
    ['Low-wavenumber integration bound [cpm] for chi_obs/chi_mle (mod_scan_calc_chi_obs.m, ' ...
     'mod_scan_calc_chi_mle.m)'], ...
    3);

registry(end+1) = entry('chi_mle_start_search', 'chi', 'chi_mle_start_search', ...
    {'PROCESS', 'CHI', 'chi_mle_start_search'}, ...
    'chi_mle grid-search low bound, as a multiplier on the chi_obs-seeded starting value (mod_scan_calc_chi_mle.m)', ...
    1e-3);

registry(end+1) = entry('chi_mle_end_search', 'chi', 'chi_mle_end_search', ...
    {'PROCESS', 'CHI', 'chi_mle_end_search'}, ...
    'chi_mle grid-search high bound, as a multiplier on the chi_obs-seeded starting value (mod_scan_calc_chi_mle.m)', ...
    1e3);

registry(end+1) = entry('contam_freq_hz', 'chi', 'contam_freq_hz', ...
    {'PROCESS', 'CHI', 'contam_freq_hz'}, ...
    ['Known FP07 electrical-contamination frequency [Hz] for this deployment - ' ...
     'mod_scan_fpo7_cutoff.m caps the noise-floor cutoff here so a fixed spectral ' ...
     'line can''t hold the smoothed spectrum above the bench noise floor and pull ' ...
     'kc out past it. Inf = no known contamination line for this deployment (no cap ' ...
     'applied) - the historical/default behavior. See docs/workflow/L2_calc_chi.md, ' ...
     '"Contamination-frequency cap" for how a real value is derived.'], ...
    Inf);

registry(end+1) = entry('Fs_epsi', 'afe', 'sample_rate', ...
    {'PROCESS', 'Fs_epsi'}, ...
    'Nominal EFE board sample rate [Hz] (mod_scan_get_spectra.m, MODsetup_define_filters.m)', ...
    320);

registry(end+1) = entry('fft_length', 'spectral', 'fft_length', ...
    {'PROCESS', 'fft_length'}, ...
    ['FFT segment length [samples] - also the Hamming taper length (no separate zero-' ...
     'padding: taper length always equals fft_length). Power-of-2 recommended for FFT ' ...
     'efficiency (not enforced - Rockland ODAS''s own get_diss_odas.m doesn''t enforce it ' ...
     'either, just isnumeric/isscalar/>=2); matches Rockland ODAS''s own field name ' ...
     '(mod_scan_get_spectra.m, MODsetup_define_filters.m)'], ...
    1024);

registry(end+1) = entry('fft_segments_per_scan', 'spectral', 'fft_segments_per_scan', ...
    {'PROCESS', 'fft_segments_per_scan'}, ...
    ['Number of Welch-averaged FFT segments per scan, at a hardcoded 50%% overlap ' ...
     '(mod_scan_get_spectra.m''s FFT_OVERLAP constant) - directly sets dof = ' ...
     '1.9*fft_segments_per_scan (processing/scans/mod_scan_dof.m, Nuttall 1971). scan_length is ' ...
     'DERIVED from this and fft_length (processing/scans/mod_scan_length_from_segments.m: ' ...
     'scan_length = fft_length*(fft_segments_per_scan+1)/2), not set directly - check the ' ...
     'resulting scan_length''s physical footprint (scan_length/Fs_epsi*fall_speed) against ' ...
     'the instrument''s own length before shipping a value, see ' ...
     'docs/concepts/spectral_windowing.md. Should be >= 3 (ATOMIX floor - matches the old ' ...
     'scan_length>=2*fft_length minimum ratio), recommended >= 5 (dof=9.5, Rockland''s ' ...
     '''recommended'' language) - Rockland''s own shipped default (quick_look.m) is ' ...
     'fft_segments_per_scan=7 (ratio=4)'], ...
    3);

registry(end+1) = entry('scan_overlap', 'spectral', 'scan_overlap', ...
    {'PROCESS', 'scan_overlap'}, ...
    ['Fraction (0-1) of scan_length overlap between successive scans along the profile ' ...
     '(mod_L2_tile_scans.m: scan_step = (1-scan_overlap)*scan_length). Matches Rockland ' ...
     'ODAS''s user-settable overlap parameter (get_diss_odas.m; their suggested default is ' ...
     'also diss_length/2)'], ...
    0.5);

registry(end+1) = entry('lowpass_factor', 'profile_detection', 'lowpass_factor', ...
    {'PROFILES', 'lowpass_factor'}, ...
    'Profiling-direction detection: lowpass cutoff period = lowpass_factor*median(dt) (mod_L1_detect_profiling_direction.m)', ...
    3);

registry(end+1) = entry('ctd_gap_factor', 'profile_detection', 'ctd_gap_factor', ...
    {'PROFILES', 'ctd_gap_factor'}, ...
    ['Profiling-direction/profile-picking: gaps in the ctd/pressure record > ctd_gap_factor*median(dt) ' ...
     'split the record, not interpolated across (mod_L1_detect_profiling_direction.m, ' ...
     'modProcess_detect_profiles.m). Named ctd_gap_factor (not gap_factor) to pair with ' ...
     'PROCESS.epsi_gap_factor below - the two operate on different timebases with different ' ...
     'consequences, so they are separate, symmetrically-named fields, not one shared threshold.'], ...
    5);

registry(end+1) = entry('buffer_bins', 'profile_detection', 'buffer_bins', ...
    {'PROFILES', 'buffer_bins'}, ...
    'Profiling-direction detection: pad each descending run by this many raw pressure samples on each side (mod_L1_detect_profiling_direction.m)', ...
    1);

registry(end+1) = entry('speedLim_down_start_m_s', 'profile_detection', 'speedLim_down_start_m_s', ...
    {'PROFILES', 'speedLim_down_start_m_s'}, ...
    'Profile-picking: dPdt threshold [dbar/s] to START a downcast run (modProcess_detect_profiles.m)', ...
    0.3);

registry(end+1) = entry('speedLim_down_end_m_s', 'profile_detection', 'speedLim_down_end_m_s', ...
    {'PROFILES', 'speedLim_down_end_m_s'}, ...
    'Profile-picking: dPdt threshold [dbar/s] to END a downcast run - lower than the start threshold, so a run continues through brief slowdowns (modProcess_detect_profiles.m)', ...
    0.1);

registry(end+1) = entry('speedLim_up_start_m_s', 'profile_detection', 'speedLim_up_start_m_s', ...
    {'PROFILES', 'speedLim_up_start_m_s'}, ...
    'Profile-picking: -dPdt threshold [dbar/s] to START an upcast run (modProcess_detect_profiles.m)', ...
    0.1);

registry(end+1) = entry('speedLim_up_end_m_s', 'profile_detection', 'speedLim_up_end_m_s', ...
    {'PROFILES', 'speedLim_up_end_m_s'}, ...
    'Profile-picking: -dPdt threshold [dbar/s] to END an upcast run (modProcess_detect_profiles.m)', ...
    0.05);

registry(end+1) = entry('minLength_m', 'profile_detection', 'minLength_m', ...
    {'PROFILES', 'minLength_m'}, ...
    'Profile-picking: minimum pressure range [dbar] for a detected run to count as a real profile (modProcess_detect_profiles.m)', ...
    10);

registry(end+1) = entry('profile_dir', 'profile_detection', 'profile_dir', ...
    {'PROFILES', 'profile_dir'}, ...
    ['Which cast direction(s) this deployment trusts enough to compute epsi spectra for - ' ...
     '''down'', ''up'', or ''both'' (MODprocess_single_L1_to_L2_profile.m). Every detected ' ...
     'cast still gets a Profile####.mat with its CTD record either way - this only gates ' ...
     'spectra, never CTD/pressure output.'], ...
    'down');

registry(end+1) = entry('epsi_gap_factor', 'spectral', 'epsi_gap_factor', ...
    {'PROCESS', 'epsi_gap_factor'}, ...
    ['Scan-window gap threshold for the epsi record: a sample-to-sample gap wider than ' ...
     'epsi_gap_factor*(1/Fs_epsi) starts a new segment_id, and no FFT window is ever built ' ...
     'spanning two segments (modProcess_extract_profile.m, mod_L2_tile_scans.m). Distinct from ' ...
     'ctd_gap_factor above - epsi is uniformly clocked hardware (nominal-rate threshold), unlike ' ...
     'the sparse/irregular ctd record (local-median threshold).'], ...
    3);

registry(end+1) = entry('epsilon_final_source', 'epsilon', 'epsilon_final_source', ...
    {'PROCESS', 'EPSILON', 'epsilon_final_source'}, ...
    ['Which epsilon estimate feeds chi_mle''s epsilon input (mean across this deployment''s ' ...
     'shear channels, omitting NaN - see mod_L2_tile_scans.m; the full profile-level ratio-' ...
     'based per-channel selection modProcess_L2_qc.m will eventually do is not built yet): ' ...
     '''epsilon_co'' (direct Nasmyth-fit) or ''epsilon_mle'' (Nasmyth MLE fit). Default ' ...
     'changed from the legacy ''epsilon_co'' to ''epsilon_mle'' once mod_scan_calc_epsilon.m ' ...
     'shipped (branch epsilon_processing), adopting Jen''s 2026 ASTRAL reprocess finding that ' ...
     'epsilon_mle is better-behaved - see PLAN.md Session Log, 2026-09-02 and 2026-09-08.'], ...
    'epsilon_mle');

registry(end+1) = entry('epsilon_stage1_kmin', 'epsilon', 'stage1_kmin', ...
    {'PROCESS', 'EPSILON', 'stage1_kmin'}, ...
    ['Low-wavenumber bound [cpm] for epsilon_obs/epsilon_obs_coh_corr''s stage-1 integration ' ...
     '(mod_scan_calc_epsilon_obs.m''s calc_epsilon_direct, ported from eps1_mmp.m) - a genuinely ' ...
     'different value from epsilon_kmin_obs (which governs stages 2-3), not a duplicate. ' ...
     'CAUTION: this and stage1_kmax together define the exact band ' ...
     '(eps_fit_shear10/shtotal_fit_shear10, mod_scan_calc_epsilon_obs.m) two empirical polynomial ' ...
     'fits were derived over - changing either away from the historical 2-10 cpm band feeds those ' ...
     'polynomials data outside their valid range, silently degrading stage 1''s first-pass eps1 ' ...
     'estimate. Made tunable (was a hardcoded literal in both eps1_mmp.m and this port) for ' ...
     'traceability/consistency with every other formerly-hardcoded epsilon/chi bound in this ' ...
     'repo - not because a different value is expected to be valid.'], ...
    2);

registry(end+1) = entry('epsilon_stage1_kmax', 'epsilon', 'stage1_kmax', ...
    {'PROCESS', 'EPSILON', 'stage1_kmax'}, ...
    'High-wavenumber bound [cpm] for epsilon_obs/epsilon_obs_coh_corr''s stage-1 integration - see epsilon_stage1_kmin for the shared CAUTION about the two empirical polynomial fits this band feeds.', ...
    10);

registry(end+1) = entry('epsilon_kmin_obs', 'epsilon', 'kmin_obs', ...
    {'PROCESS', 'EPSILON', 'kmin_obs'}, ...
    ['Low-wavenumber integration bound [cpm] for epsilon_obs/epsilon_obs_coh_corr''s stages 2-3 ' ...
     '(mod_scan_calc_epsilon_obs.m) - mirrors PROCESS.CHI.kmin_obs, but a separate field since ' ...
     'shear and fpo7 are independent channels that could in principle need different values. ' ...
     'MOD_fish_lib''s eps1_mmp.m hardcoded this at 3 cpm (not a caller-supplied argument at ' ...
     'all) - made tunable here, same precedent as chi''s own kmin_obs field.'], ...
    3);

registry(end+1) = entry('contam_freq_hz_shear', 'epsilon', 'contam_freq_hz', ...
    {'PROCESS', 'EPSILON', 'contam_freq_hz'}, ...
    ['Known shear-channel vibration/electrical contamination frequency [Hz] for this ' ...
     'deployment - mod_scan_calc_epsilon_obs.m caps the integration upper bound here ' ...
     '(kmax = contam_freq_hz/abs(w)), the shear-channel analog of PROCESS.CHI.contam_freq_hz ' ...
     '(MOD_fish_lib''s Meta_Data.PROCESS.ctd_fc). Inf = no known contamination line for this ' ...
     'deployment (no cap applied) - the historical/default behavior.'], ...
    Inf);

registry(end+1) = entry('oakey_lc_m', 'epsilon', 'oakey_lc_m', ...
    {'PROCESS', 'EPSILON', 'oakey_lc_m'}, ...
    ['Shear probe''s spatial cutoff wavelength [m] in the Oakey (1982) dynamic-response ' ...
     'transfer function (mod_scan_shear_transfer_function.m). MOD_fish_lib''s haf_oakey.m ' ...
     'hardcoded this at 0.02 - made tunable here, same precedent as chi''s ' ...
     'time_constant_s/fall_speed_exponent fields.'], ...
    0.02);

registry(end+1) = entry('coherence_fmin_hz', 'epsilon', 'coherence_fmin_hz', ...
    {'PROCESS', 'EPSILON', 'coherence_fmin_hz'}, ...
    ['Low end of the frequency band mod_scan_shear_accel_coherence.m''s band-integrated ' ...
     'coherence diagnostic (spectra.(ch)_coh_a3_sum) sums over - not itself consumed by the ' ...
     'epsilon calculation (which uses the full per-frequency coherence vector, not this sum). ' ...
     'MOD_fish_lib''s mod_efe_scan_coherence.m used Meta_Data.PROCESS.fc1/.fc2 for the same ' ...
     'band - no historical numeric default found in this repo''s reference deployments, so this ' ...
     'suggested_default is a placeholder pending a real value; see docs/workflow/L2_calc_eps.md.'], ...
    0);

registry(end+1) = entry('coherence_fmax_hz', 'epsilon', 'coherence_fmax_hz', ...
    {'PROCESS', 'EPSILON', 'coherence_fmax_hz'}, ...
    ['High end of the frequency band mod_scan_shear_accel_coherence.m''s band-integrated ' ...
     'coherence diagnostic sums over - see coherence_fmin_hz. Placeholder default pending a ' ...
     'real per-deployment value; see docs/workflow/L2_calc_eps.md.'], ...
    Inf);

registry(end+1) = entry('mle_start_search', 'epsilon', 'mle_start_search', ...
    {'PROCESS', 'EPSILON', 'mle_start_search'}, ...
    ['epsilon_mle grid-search low bound, as a multiplier on the epsilon_obs_coh_corr-seeded starting ' ...
     'value (mod_scan_calc_epsilon_mle.m, processing/scans/mod_scan_mle_grid_search.m). Mirrors ' ...
     'PROCESS.CHI.chi_mle_start_search but registered separately - MOD_fish_lib''s epsilon MLE ' ...
     'search used a narrower one-decade-each-side range (0.1/10) than chi''s three-decade range ' ...
     '(1e-3/1e3), a real, deliberate difference in the legacy code, not an oversight to reconcile.'], ...
    0.1);

registry(end+1) = entry('mle_end_search', 'epsilon', 'mle_end_search', ...
    {'PROCESS', 'EPSILON', 'mle_end_search'}, ...
    'epsilon_mle grid-search high bound, as a multiplier on the epsilon_obs_coh_corr-seeded starting value - see mle_start_search.', ...
    10);

registry(end+1) = entry('kmin_mle', 'epsilon', 'kmin_mle', ...
    {'PROCESS', 'EPSILON', 'kmin_mle'}, ...
    ['Low-wavenumber bound [cpm] for the epsilon MLE fit (mirrors PROCESS.CHI.kmin_obs). ' ...
     'Legacy mod_efe_scan_epsilon.m used a computed SpecObs.kli(1), not a fixed constant, ' ...
     'so there is no historical scalar default to carry forward - 5 here is Jen''s 2026 ' ...
     'ASTRAL fork value (mirroring her chi-side kmin=5), not yet independently verified for ' ...
     'this repo. See PLAN.md Session Log, 2026-09-02.'], ...
    5);

registry(end+1) = entry('qc_accel_method', 'epsilon', 'qc_accel_method', ...
    {'PROCESS', 'EPSILON', 'qc_accel_method'}, ...
    ['Which acceleration-power QC check flags a scan/profile: ''rms_std'' (log10(sumPa) > ' ...
     '-rms + qc_accel_nstd*std, legacy default) or ''threshold'' (sumPa > qc_accel_threshold, ' ...
     'Jen''s 2026 ASTRAL fork - found the rms_std version throwing out good data on that ' ...
     'deployment). See PLAN.md Session Log, 2026-09-02.'], ...
    'rms_std');

registry(end+1) = entry('qc_accel_threshold', 'epsilon', 'qc_accel_threshold', ...
    {'PROCESS', 'EPSILON', 'qc_accel_threshold'}, ...
    ['Fixed sumPa threshold used when qc_accel_method=''threshold''. Jen''s 2026 ASTRAL ' ...
     'fork value - deployment-specific, not verified elsewhere.'], ...
    1e-5);

registry(end+1) = entry('qc_accel_nstd', 'epsilon', 'qc_accel_nstd', ...
    {'PROCESS', 'EPSILON', 'qc_accel_nstd'}, ...
    ['Std-dev multiplier used when qc_accel_method=''rms_std'' (legacy hardcoded value, ' ...
     'never previously tunable).'], ...
    2);

registry(end+1) = entry('dz_m', 'grid', 'dz_m', ...
    {'PROCESS', 'GRID', 'dz_m'}, ...
    ['Vertical grid spacing [m] for L2->L3 profile gridding. 1 m is the legacy default; ' ...
     'Jen''s 2026 ASTRAL fork used 0.5 m, enabled by that deployment''s smaller fft_length. See ' ...
     'PLAN.md Session Log, 2026-09-02.'], ...
    1);

end %end function

function e = entry(name, yaml_section, yaml_key, metadata_path, description, suggested_default)
e.name = name;
e.yaml_section = yaml_section;
e.yaml_key = yaml_key;
e.metadata_path = metadata_path;
e.description = description;
e.suggested_default = suggested_default;
end
