function registry = MODsetup_metadata_field_registry()
% MODsetup_metadata_field_registry        Part of MOD_fish_processing
%
% registry = MODsetup_metadata_field_registry()
%
% DESCRIPTION
%   The single source of truth for every deployment-tunable value this
%   repo currently knows how to read from setup.yml: where it lives in
%   setup.yml (yaml_section/yaml_key), where it lives in metadata
%   (metadata_path), what it's for, and what value it has historically
%   defaulted to. Consumed by MODsetup_validate_metadata.m (looks up each
%   requested name to know what to check/prompt for) and
%   MODsetup_write_yaml_value.m callers (to know which section/key to
%   write). Not consumed by MODsetup_read_yaml.m - that function only ever
%   sets a metadata field when setup.yml actually declares it (see its
%   header); suggested_default here is purely the starting value shown in
%   MODsetup_prompt_value.m's popup, never applied silently.
%
%   The 10 PROCESS.CHI entries, the 7 profile-picking entries
%   (modProcess_detect_profiles.m), and epsi_gap_factor
%   (modProcess_extract_profile.m) have real MODsetup_validate_metadata.m
%   call sites. Fs_epsi/nfft/dof/PROFILES.lowpass_factor/.ctd_gap_factor/
%   .buffer_bins are populated so this table stays a complete, accurate
%   record of every yaml-configurable value, even though wiring their
%   consumers (mod_scan_get_spectra.m, mod_L1_detect_profiling_direction.m)
%   is a deferred follow-up - see PLAN.md.
%
% OUTPUTS
%   registry - struct array (1 x 23), one entry per value:
%     name              - short key used in MODsetup_validate_metadata.m's
%                          list_of_variables, e.g. 'kmin_obs'
%     yaml_section       - top-level setup.yml block, e.g. 'chi'
%     yaml_key           - key within that block, e.g. 'kmin_obs'
%     metadata_path      - cellstr of nested metadata field names, e.g.
%                          {'PROCESS','CHI','kmin_obs'}
%     description        - human-readable, shown in MODsetup_prompt_value.m
%     suggested_default  - this function's historical hardcoded value,
%                          shown as the prompt's starting value only
%
% CALLED BY
%   MODsetup_validate_metadata.m
%
% CALLS
%   (none)
%
% Multiscale Ocean Dynamics (MOD) Group, Scripps Institution of Oceanography

registry = struct('name', {}, 'yaml_section', {}, 'yaml_key', {}, ...
    'metadata_path', {}, 'description', {}, 'suggested_default', {});

registry(end+1) = entry('time_constant_s', 'chi', 'time_constant_s', ...
    {'PROCESS', 'CHI', 'time_constant_s'}, ...
    ['FP07 time-constant coefficient tau0 [s] (mod_scan_fpo7_transfer_function.m: ' ...
     'tau = tau0*abs(w)^exponent)'], ...
    0.0083);

registry(end+1) = entry('fall_speed_exponent', 'chi', 'fall_speed_exponent', ...
    {'PROCESS', 'CHI', 'fall_speed_exponent'}, ...
    ['FP07 time-constant fall-speed exponent (mod_scan_fpo7_transfer_function.m: ' ...
     'tau = tau0*abs(w)^exponent)'], ...
    -0.32);

registry(end+1) = entry('noise_adjusted_to_f', 'chi', 'noise_adjusted_to_f', ...
    {'PROCESS', 'CHI', 'noise_adjusted_to_f'}, ...
    ['Fraction of f(end) (Nyquist) above which mod_scan_fpo7_cutoff.m normalizes ' ...
     'the observed spectrum onto the bench noise floor''s scale'], ...
    0.7);

registry(end+1) = entry('n_smooth_f_spectrum', 'chi', 'n_smooth_f_spectrum', ...
    {'PROCESS', 'CHI', 'n_smooth_f_spectrum'}, ...
    ['movmean smoothing window [bins] applied to the observed spectrum before ' ...
     'the noise-floor search (mod_scan_fpo7_cutoff.m)'], ...
    15);

registry(end+1) = entry('sn_min', 'chi', 'sn_min', ...
    {'PROCESS', 'CHI', 'sn_min'}, ...
    ['Signal-to-noise multiplier: the noise-floor cutoff is where the smoothed ' ...
     'spectrum drops below sn_min x the bench noise floor (mod_scan_fpo7_cutoff.m)'], ...
    3);

registry(end+1) = entry('n_skip', 'chi', 'n_skip', ...
    {'PROCESS', 'CHI', 'n_skip'}, ...
    'Number of lowest-frequency bins excluded from the noise-floor search (mod_scan_fpo7_cutoff.m)', ...
    2);

registry(end+1) = entry('hamming_window_length_nfft', 'chi', 'hamming_window_length_nfft', ...
    {'PROCESS', 'CHI', 'hamming_window_length_nfft'}, ...
    ['pwelch Hamming window length, as a fraction of nfft (mod_scan_get_spectra.m: ' ...
     'window_length = hamming_window_length_nfft*nfft)'], ...
    1);

registry(end+1) = entry('kmin_obs', 'chi', 'kmin_obs', ...
    {'PROCESS', 'CHI', 'kmin_obs'}, ...
    ['Low-wavenumber integration bound [cpm] for chi_obs/chi_mle (mod_scan_calc_chi_obs.m, ' ...
     'mod_scan_calc_chi_mle.m)'], ...
    3);

registry(end+1) = entry('chi_mle_start_search', 'chi', 'chi_mle_start_search', ...
    {'PROCESS', 'CHI', 'chi_mle_start_search'}, ...
    'chi_mle grid-search low bound, as a multiplier on the chi_obs-seeded starting value (mod_scan_calc_chi_mle.m)', ...
    1e-3);

registry(end+1) = entry('chi_mle_end_search', 'chi', 'chi_mle_end_search', ...
    {'PROCESS', 'CHI', 'chi_mle_end_search'}, ...
    'chi_mle grid-search high bound, as a multiplier on the chi_obs-seeded starting value (mod_scan_calc_chi_mle.m)', ...
    1e3);

registry(end+1) = entry('Fs_epsi', 'afe', 'sample_rate', ...
    {'PROCESS', 'Fs_epsi'}, ...
    'Nominal EFE board sample rate [Hz] (mod_scan_get_spectra.m, MODsetup_define_filters.m)', ...
    320);

registry(end+1) = entry('nfft', 'spectral', 'nfft', ...
    {'PROCESS', 'nfft'}, ...
    'pwelch FFT length [samples] (mod_scan_get_spectra.m, MODsetup_define_filters.m)', ...
    1024);

registry(end+1) = entry('dof', 'spectral', 'dof', ...
    {'PROCESS', 'dof'}, ...
    ['Degrees of freedom of the power spectrum estimate - scan tiling uses ' ...
     'N_epsi=(dof-1)*nfft; mod_scan_calc_chi_mle.m''s MLE weighting also reads it directly'], ...
    3);

registry(end+1) = entry('lowpass_factor', 'profile_detection', 'lowpass_factor', ...
    {'PROFILES', 'lowpass_factor'}, ...
    'Profiling-direction detection: lowpass cutoff period = lowpass_factor*median(dt) (mod_L1_detect_profiling_direction.m)', ...
    3);

registry(end+1) = entry('ctd_gap_factor', 'profile_detection', 'ctd_gap_factor', ...
    {'PROFILES', 'ctd_gap_factor'}, ...
    ['Profiling-direction/profile-picking: gaps in the ctd/pressure record > ctd_gap_factor*median(dt) ' ...
     'split the record, not interpolated across (mod_L1_detect_profiling_direction.m, ' ...
     'modProcess_detect_profiles.m). Named ctd_gap_factor (not gap_factor) to pair with ' ...
     'PROCESS.epsi_gap_factor below - the two operate on different timebases with different ' ...
     'consequences, so they are separate, symmetrically-named fields, not one shared threshold.'], ...
    5);

registry(end+1) = entry('buffer_bins', 'profile_detection', 'buffer_bins', ...
    {'PROFILES', 'buffer_bins'}, ...
    'Profiling-direction detection: pad each descending run by this many raw pressure samples on each side (mod_L1_detect_profiling_direction.m)', ...
    1);

registry(end+1) = entry('speedLim_down_start_m_s', 'profile_detection', 'speedLim_down_start_m_s', ...
    {'PROFILES', 'speedLim_down_start_m_s'}, ...
    'Profile-picking: dPdt threshold [dbar/s] to START a downcast run (modProcess_detect_profiles.m)', ...
    0.3);

registry(end+1) = entry('speedLim_down_end_m_s', 'profile_detection', 'speedLim_down_end_m_s', ...
    {'PROFILES', 'speedLim_down_end_m_s'}, ...
    'Profile-picking: dPdt threshold [dbar/s] to END a downcast run - lower than the start threshold, so a run continues through brief slowdowns (modProcess_detect_profiles.m)', ...
    0.1);

registry(end+1) = entry('speedLim_up_start_m_s', 'profile_detection', 'speedLim_up_start_m_s', ...
    {'PROFILES', 'speedLim_up_start_m_s'}, ...
    'Profile-picking: -dPdt threshold [dbar/s] to START an upcast run (modProcess_detect_profiles.m)', ...
    0.1);

registry(end+1) = entry('speedLim_up_end_m_s', 'profile_detection', 'speedLim_up_end_m_s', ...
    {'PROFILES', 'speedLim_up_end_m_s'}, ...
    'Profile-picking: -dPdt threshold [dbar/s] to END an upcast run (modProcess_detect_profiles.m)', ...
    0.05);

registry(end+1) = entry('minLength_m', 'profile_detection', 'minLength_m', ...
    {'PROFILES', 'minLength_m'}, ...
    'Profile-picking: minimum pressure range [dbar] for a detected run to count as a real profile (modProcess_detect_profiles.m)', ...
    10);

registry(end+1) = entry('profile_dir', 'profile_detection', 'profile_dir', ...
    {'PROFILES', 'profile_dir'}, ...
    'Profile-picking: which direction(s) to keep as output profiles - ''down'', ''up'', or ''both'' (modProcess_detect_profiles.m)', ...
    'down');

registry(end+1) = entry('epsi_gap_factor', 'spectral', 'epsi_gap_factor', ...
    {'PROCESS', 'epsi_gap_factor'}, ...
    ['Scan-window gap threshold for the epsi record: a sample-to-sample gap wider than ' ...
     'epsi_gap_factor*(1/Fs_epsi) starts a new segment_id, and no FFT window is ever built ' ...
     'spanning two segments (modProcess_extract_profile.m, mod_L2_tile_scans.m). Distinct from ' ...
     'ctd_gap_factor above - epsi is uniformly clocked hardware (nominal-rate threshold), unlike ' ...
     'the sparse/irregular ctd record (local-median threshold).'], ...
    3);

end %end function

function e = entry(name, yaml_section, yaml_key, metadata_path, description, suggested_default)
e.name = name;
e.yaml_section = yaml_section;
e.yaml_key = yaml_key;
e.metadata_path = metadata_path;
e.description = description;
e.suggested_default = suggested_default;
end
